/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.util;

import java.awt.Color;
import view.notification.NotificationType;
import view.notification.NotificationEventsInterface;

/**
 *
 * @author sergi
 */
public class Notification extends javax.swing.JPanel {

    private NotificationEventsInterface notifyInterface;

    /**
     * Creates new form Notify
     */
    public Notification(NotificationType notificationType, String message) {
        initComponents();
        defineType(notificationType);
        labelText.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 0));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(10243213, 31));
        setMinimumSize(new java.awt.Dimension(200, 31));
        setPreferredSize(new java.awt.Dimension(200, 31));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -2, -1, 30));

        labelText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelText.setText("Teste");
        add(labelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        notifyInterface.onCloseNotification();
    }//GEN-LAST:event_jLabel1MousePressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        notifyInterface.onCloseNotification();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelText;
    // End of variables declaration//GEN-END:variables

    private void defineType(NotificationType notificationType) {
        this.setBackground(notificationType.getColor());
    }

    public void setInterface(NotificationEventsInterface notificationInterface) {
        this.notifyInterface = notificationInterface;
    }

}
